# Generated by Django 5.0.6 on 2025-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Roll_no', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Course', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
