# Generated by Django 5.0.6 on 2025-08-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Employee_id', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Department', models.CharField(max_length=50)),
            ],
        ),
    ]
